//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSS.Areas.CaiWuGuanLi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Access
    {
        public string AccessID { get; set; }
        public string AccessType { get; set; }
        public Nullable<System.DateTime> AccessDate { get; set; }
        public Nullable<decimal> AccessMoeny { get; set; }
        public string AccessRemark { get; set; }
        public string AccessState { get; set; }
        public Nullable<int> UsersID { get; set; }
        public Nullable<int> Eid { get; set; }
        public Nullable<int> BankID { get; set; }
    }
}
