//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSS.Areas.CaiWuGuanLi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank
    {
        public int BankID { get; set; }
        public string BankName { get; set; }
        public string OpenAccount { get; set; }
        public string OpenBank { get; set; }
        public string Account { get; set; }
        public Nullable<decimal> BankMoney { get; set; }
        public Nullable<bool> IsStop { get; set; }
    }
}
