//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSS.Areas.CaiWuGuanLi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Eid { get; set; }
        public string EName { get; set; }
        public string ESex { get; set; }
        public Nullable<System.DateTime> EBorn { get; set; }
        public string Email { get; set; }
        public string ETel { get; set; }
        public string EAddress { get; set; }
        public string EQQ { get; set; }
        public string EWay { get; set; }
        public Nullable<int> Eqcyf { get; set; }
        public Nullable<double> Eqcyfl { get; set; }
        public string ERemark { get; set; }
        public Nullable<int> EmId { get; set; }
    }
}
