//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSS.Areas.CaiWuGuanLi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Income
    {
        public string IncomeID { get; set; }
        public string IncomeName { get; set; }
        public Nullable<System.DateTime> IncomeDate { get; set; }
        public Nullable<decimal> IncomeMoney { get; set; }
        public string IncomeRemark { get; set; }
        public string IncomeType { get; set; }
        public Nullable<int> BankID { get; set; }
        public Nullable<int> UsersID { get; set; }
        public Nullable<int> Employee { get; set; }
    }
}
