//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSS.Areas.CaiWuGuanLi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyEF : DbContext
    {
        public MyEF()
            : base("name=MyEF")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bank> Bank { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Income> Income { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Pay> Pay { get; set; }
        public virtual DbSet<Access> Access { get; set; }
    }
}
