//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSS.Areas.CaiWuGuanLi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay
    {
        public string PayID { get; set; }
        public string PayName { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public Nullable<decimal> PayMoney { get; set; }
        public string PayRemark { get; set; }
        public string PayType { get; set; }
        public Nullable<int> BankID { get; set; }
        public Nullable<int> UsersID { get; set; }
        public Nullable<int> Employee { get; set; }
    }
}
